- name: build job file from template
  ansible.builtin.templates:
    src: mbranch.xml
    desc: /tmp/mbranch.xml


- name: Create a multi branch pipeline
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/mbranch.xml') }}"
    name: "ci-pipelines/{{item.name}}"
    password: Admin123
    url: http://172.31.12.244:8080
    user: Admin
